services:
  nask-task-app:
    volumes:
      - ./nask_task_app/app:/app
    env_file:
      - .envs/.dev_docker
    ports:
      - 8000:8000

  redis:
    container_name: nask-task-redis
    image: redis:7-alpine
    ports:
      - 6379:6379

  rabbitmq:
    ports:
      - 15672:15672
      - 5672:5672
    restart: always

  celery:
    volumes:
      - ./nask_task_app/app:/app
    env_file:
      - .envs/.dev_docker

  flower:
    volumes:
      - ./nask_task_app/app:/app
    env_file:
      - .envs/.dev_docker
    ports:
      - 5555:5555
