###
GET http://127.0.0.1:8000/
Accept: application/json

###
POST http://127.0.0.1:8000/
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "type": "prime",
  "notify_url": "http://127.0.0.1:8000/",
  "status": "PENDING",
  "payload": {
    "input": 101
  }
}

###
GET http://127.0.0.1:8000/api/tasks
Accept: application/json

###
GET http://127.0.0.1:8000/api/tasks/5b200284-6d2e-473e-b221-1b3469e08e70
Accept: application/json

###
POST http://127.0.0.1:8000/api/tasks
Accept: application/json
Content-Type: application/json

{
  "type": "prime",
  "notify_url": "http://127.0.0.1:8000/",
  "payload": {
    "input": 101
  }
}

###
POST http://127.0.0.1:8000/api/tasks
Accept: application/json
Content-Type: application/json

{
  "type": "fibonacci",
  "notify_url": "http://127.0.0.1:8000/",
  "payload": {
    "input": 20
  }
}
